/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppNewsIndexRouteImport } from './routes/_app/news/index'
import { Route as AppNewsPreviewIdRouteImport } from './routes/_app/news/preview.$id'
import { Route as AppNewsEditorNewRouteImport } from './routes/_app/news/editor.new'
import { Route as AppNewsEditorIdRouteImport } from './routes/_app/news/editor.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsPreviewIdRoute = AppNewsPreviewIdRouteImport.update({
  id: '/news/preview/$id',
  path: '/news/preview/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsEditorNewRoute = AppNewsEditorNewRouteImport.update({
  id: '/news/editor/new',
  path: '/news/editor/new',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsEditorIdRoute = AppNewsEditorIdRouteImport.update({
  id: '/news/editor/$id',
  path: '/news/editor/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/news/': typeof AppNewsIndexRoute
  '/news/editor/$id': typeof AppNewsEditorIdRoute
  '/news/editor/new': typeof AppNewsEditorNewRoute
  '/news/preview/$id': typeof AppNewsPreviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/news': typeof AppNewsIndexRoute
  '/news/editor/$id': typeof AppNewsEditorIdRoute
  '/news/editor/new': typeof AppNewsEditorNewRoute
  '/news/preview/$id': typeof AppNewsPreviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/_app/news/editor/$id': typeof AppNewsEditorIdRoute
  '/_app/news/editor/new': typeof AppNewsEditorNewRoute
  '/_app/news/preview/$id': typeof AppNewsPreviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/saved'
    | '/settings'
    | '/users'
    | '/news/'
    | '/news/editor/$id'
    | '/news/editor/new'
    | '/news/preview/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/saved'
    | '/settings'
    | '/users'
    | '/news'
    | '/news/editor/$id'
    | '/news/editor/new'
    | '/news/preview/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/news/'
    | '/_app/news/editor/$id'
    | '/_app/news/editor/new'
    | '/_app/news/preview/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/preview/$id': {
      id: '/_app/news/preview/$id'
      path: '/news/preview/$id'
      fullPath: '/news/preview/$id'
      preLoaderRoute: typeof AppNewsPreviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/editor/new': {
      id: '/_app/news/editor/new'
      path: '/news/editor/new'
      fullPath: '/news/editor/new'
      preLoaderRoute: typeof AppNewsEditorNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/editor/$id': {
      id: '/_app/news/editor/$id'
      path: '/news/editor/$id'
      fullPath: '/news/editor/$id'
      preLoaderRoute: typeof AppNewsEditorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
  AppNewsEditorIdRoute: typeof AppNewsEditorIdRoute
  AppNewsEditorNewRoute: typeof AppNewsEditorNewRoute
  AppNewsPreviewIdRoute: typeof AppNewsPreviewIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
  AppNewsEditorIdRoute: AppNewsEditorIdRoute,
  AppNewsEditorNewRoute: AppNewsEditorNewRoute,
  AppNewsPreviewIdRoute: AppNewsPreviewIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
