-- =========================================================
-- Align Lovable Cloud schema with Flutter Supabase schema
-- =========================================================

-- Drop old objects from previous setup
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP FUNCTION IF EXISTS public.get_my_roles() CASCADE;
DROP FUNCTION IF EXISTS public.has_role(uuid, app_role) CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP TYPE IF EXISTS public.app_role CASCADE;
DROP TYPE IF EXISTS public.article_status CASCADE;

-- =========================================================
-- profiles
-- =========================================================
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NULL,
  full_name text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  professions text[] NULL DEFAULT '{}'::text[],
  interests text[] NULL DEFAULT '{}'::text[],
  city text NULL,
  country text NULL,
  latitude double precision NULL,
  longitude double precision NULL,
  location_updated_at timestamp with time zone NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- =========================================================
-- user_roles  (text role, one per user)
-- =========================================================
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NULL,
  role text NULL DEFAULT 'user'::text,
  created_at timestamp without time zone NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_key UNIQUE (user_id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT user_roles_role_check CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text])))
);

-- =========================================================
-- news
-- =========================================================
CREATE TABLE public.news (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NULL,
  description text NULL,
  image_url text NULL,
  url text NULL,
  source text NULL,
  category text NULL DEFAULT 'general'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  key_points jsonb NULL,
  action_points jsonb NULL,
  summary text NULL,
  country text NULL,
  state text NULL,
  district text NULL,
  taluka text NULL,
  city text NULL,
  pincode character varying(10) NULL,
  CONSTRAINT news_pkey PRIMARY KEY (id),
  CONSTRAINT news_url_key UNIQUE (url)
);
CREATE INDEX IF NOT EXISTS idx_news_location ON public.news USING btree (country, state, district, city);

-- =========================================================
-- saved_articles
-- =========================================================
CREATE TABLE public.saved_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL DEFAULT gen_random_uuid(),
  article_id text NULL,
  title text NULL,
  description text NULL,
  image_url text NULL,
  source text NULL,
  CONSTRAINT saved_articles_pkey PRIMARY KEY (id),
  CONSTRAINT saved_articles_user_article_unique UNIQUE (user_id, article_id)
);

-- =========================================================
-- password_otps
-- =========================================================
CREATE TABLE public.password_otps (
  email text NOT NULL,
  otp text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used boolean NULL DEFAULT false,
  CONSTRAINT password_otps_pkey PRIMARY KEY (email)
);

-- =========================================================
-- Helper: is_admin (SECURITY DEFINER, avoids RLS recursion)
-- =========================================================
CREATE OR REPLACE FUNCTION public.is_admin(_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.user_roles WHERE user_id = auth.uid() LIMIT 1;
$$;

-- =========================================================
-- Auto-create profile + default role on signup
-- =========================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user')
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================
-- RLS
-- =========================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_otps ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY "profiles select own or admin"
  ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "profiles insert own"
  ON public.profiles FOR INSERT TO authenticated
  WITH CHECK (id = auth.uid());
CREATE POLICY "profiles update own or admin"
  ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "profiles delete admin"
  ON public.profiles FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()));

-- user_roles
CREATE POLICY "roles read own or admin"
  ON public.user_roles FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "roles insert admin"
  ON public.user_roles FOR INSERT TO authenticated
  WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "roles update admin"
  ON public.user_roles FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()));
CREATE POLICY "roles delete admin"
  ON public.user_roles FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()));

-- news: everyone authenticated can read; only admins can write
CREATE POLICY "news read authenticated"
  ON public.news FOR SELECT TO authenticated
  USING (true);
CREATE POLICY "news insert admin"
  ON public.news FOR INSERT TO authenticated
  WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "news update admin"
  ON public.news FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()));
CREATE POLICY "news delete admin"
  ON public.news FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()));

-- saved_articles: user manages own; admin can view all
CREATE POLICY "saved select own or admin"
  ON public.saved_articles FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "saved insert own"
  ON public.saved_articles FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "saved delete own or admin"
  ON public.saved_articles FOR DELETE TO authenticated
  USING (user_id = auth.uid() OR public.is_admin(auth.uid()));

-- password_otps: locked down (server-side only via service role)
CREATE POLICY "otps admin read"
  ON public.password_otps FOR SELECT TO authenticated
  USING (public.is_admin(auth.uid()));
