
-- ============================================================
-- 1. CLEANUP: drop old articles table from previous iteration
-- ============================================================
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TYPE IF EXISTS public.article_status CASCADE;

-- Drop existing helpers that we'll recreate with new signatures
DROP FUNCTION IF EXISTS public.get_my_roles() CASCADE;
DROP FUNCTION IF EXISTS public.has_role(uuid, app_role) CASCADE;
DROP FUNCTION IF EXISTS public.has_role(app_role, uuid) CASCADE;
DROP TYPE IF EXISTS public.app_role CASCADE;

-- ============================================================
-- 2. NEWS table — matches Flutter + created_by for ownership
-- ============================================================
DROP TABLE IF EXISTS public.news CASCADE;
CREATE TABLE public.news (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NULL,
  description text NULL,
  image_url text NULL,
  url text NULL,
  source text NULL,
  category text NULL DEFAULT 'general'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  key_points jsonb NULL,
  action_points jsonb NULL,
  summary text NULL,
  country text NULL,
  state text NULL,
  district text NULL,
  taluka text NULL,
  city text NULL,
  pincode varchar(10) NULL,
  created_by uuid NULL,  -- NEW: ownership column for reporter scoping
  CONSTRAINT news_pkey PRIMARY KEY (id),
  CONSTRAINT news_url_key UNIQUE (url)
);
CREATE INDEX IF NOT EXISTS idx_news_location
  ON public.news USING btree (country, state, district, city);
CREATE INDEX IF NOT EXISTS idx_news_created_by ON public.news (created_by);
CREATE INDEX IF NOT EXISTS idx_news_created_at ON public.news (created_at DESC);

-- ============================================================
-- 3. PROFILES table — exact Flutter shape
-- ============================================================
DROP TABLE IF EXISTS public.profiles CASCADE;
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NULL,
  full_name text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  professions text[] NULL DEFAULT '{}'::text[],
  interests text[] NULL DEFAULT '{}'::text[],
  city text NULL,
  country text NULL,
  latitude double precision NULL,
  longitude double precision NULL,
  location_updated_at timestamp with time zone NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ============================================================
-- 4. USER_ROLES — Flutter shape + add 'reporter'
-- ============================================================
DROP TABLE IF EXISTS public.user_roles CASCADE;
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NULL,
  role text NULL DEFAULT 'user'::text,
  created_at timestamp without time zone NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_key UNIQUE (user_id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT user_roles_role_check CHECK (role = ANY (ARRAY['user'::text, 'admin'::text, 'reporter'::text]))
);

-- ============================================================
-- 5. SAVED_ARTICLES — exact Flutter shape
-- ============================================================
DROP TABLE IF EXISTS public.saved_articles CASCADE;
CREATE TABLE public.saved_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL DEFAULT gen_random_uuid(),
  article_id text NULL,
  title text NULL,
  description text NULL,
  image_url text NULL,
  source text NULL,
  CONSTRAINT saved_articles_pkey PRIMARY KEY (id),
  CONSTRAINT saved_articles_user_article_unique UNIQUE (user_id, article_id)
);

-- ============================================================
-- 6. PASSWORD_OTPS — exact Flutter shape
-- ============================================================
DROP TABLE IF EXISTS public.password_otps CASCADE;
CREATE TABLE public.password_otps (
  email text NOT NULL,
  otp text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used boolean NULL DEFAULT false,
  CONSTRAINT password_otps_pkey PRIMARY KEY (email)
);

-- ============================================================
-- 7. ADS table — new (for the Ads module in the React panel)
-- ============================================================
CREATE TABLE public.ads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NULL,
  image_url text NULL,
  link_url text NULL,
  placement text NULL DEFAULT 'feed',  -- feed, sidebar, banner, etc.
  active boolean NOT NULL DEFAULT true,
  starts_at timestamp with time zone NULL,
  ends_at timestamp with time zone NULL,
  created_by uuid NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_ads_active ON public.ads (active) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_ads_created_by ON public.ads (created_by);

-- ============================================================
-- 8. HELPER FUNCTIONS (security definer to avoid RLS recursion)
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_admin(_user_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.has_role(_role text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = _role
  );
$$;

-- Returns array of roles for current user (the React panel calls this)
CREATE OR REPLACE FUNCTION public.get_my_roles()
RETURNS text[]
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT COALESCE(array_agg(role), ARRAY[]::text[])
  FROM public.user_roles
  WHERE user_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT role FROM public.user_roles WHERE user_id = auth.uid() LIMIT 1;
$$;

-- ============================================================
-- 9. TIMESTAMP TRIGGER + AUTO-CREATE PROFILE/ROLE ON SIGNUP
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE TRIGGER ads_set_updated_at BEFORE UPDATE ON public.ads
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user')
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- 10. ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;

-- NEWS: any authenticated reads; admins do all; reporters manage own
CREATE POLICY "news read authenticated" ON public.news
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "news insert admin or reporter own" ON public.news
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin(auth.uid()) OR (public.has_role('reporter') AND created_by = auth.uid()));
CREATE POLICY "news update admin or own" ON public.news
  FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()) OR created_by = auth.uid());
CREATE POLICY "news delete admin or own" ON public.news
  FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()) OR created_by = auth.uid());

-- ADS: same model as news
CREATE POLICY "ads read authenticated" ON public.ads
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "ads insert admin or reporter own" ON public.ads
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin(auth.uid()) OR (public.has_role('reporter') AND created_by = auth.uid()));
CREATE POLICY "ads update admin or own" ON public.ads
  FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()) OR created_by = auth.uid());
CREATE POLICY "ads delete admin or own" ON public.ads
  FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()) OR created_by = auth.uid());

-- PROFILES
CREATE POLICY "profiles select own or admin" ON public.profiles
  FOR SELECT TO authenticated USING (id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "profiles insert own" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "profiles update own or admin" ON public.profiles
  FOR UPDATE TO authenticated USING (id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "profiles delete admin" ON public.profiles
  FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));

-- USER_ROLES
CREATE POLICY "roles read own or admin" ON public.user_roles
  FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "roles insert admin" ON public.user_roles
  FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "roles update admin" ON public.user_roles
  FOR UPDATE TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "roles delete admin" ON public.user_roles
  FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));

-- SAVED_ARTICLES
CREATE POLICY "saved select own or admin" ON public.saved_articles
  FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "saved insert own" ON public.saved_articles
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "saved delete own or admin" ON public.saved_articles
  FOR DELETE TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));

-- PASSWORD_OTPS — admin read only
CREATE POLICY "otps admin read" ON public.password_otps
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
